site_name: Quix Docs
site_description: Quix CLI Documentation

docs_dir: docs/
repo_name: quixio/quix-cli
repo_url: https://github.com/quixio/quix-cli
edit_uri: tree/main/docs

exclude_docs: '*.gen.md'

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - mdx_include:
      recursive_relative_path: true
      base_path: docs

