site_name: Quix Docs
site_description: Quix CLI Documentation
docs_dir: docs/
repo_name: quixio/quix-cli
repo_url: https://github.com/quixio/quix-cli
edit_uri: tree/main/docs
exclude_docs: '*.gen.md'
theme:
  name: material
  features:
  - navigation.path
  - navigation.indexes
markdown_extensions:
- attr_list
- md_in_html
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- admonition
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
- pymdownx.details: 
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
plugins:
- include-markdown
nav:
- 'Overview': 'overview.md'
- 'Quickstart': 'cli-quickstart.md'
- 'Tutorials':
  - 'Using the CLI with a template': 'cli-template.md'
  - 'Using the CLI with GitHub Actions': 'cli-github-actions.md'
- Reference:
  - applications:
    - get: Reference/applications/get.md
    - list: Reference/applications/list.md
    - library:
      - list: Reference/applications/library/list.md
  - login: Reference/login.md
  - contexts:
    - create: Reference/contexts/create.md
    - current: Reference/contexts/current.md
    - list: Reference/contexts/list.md
    - delete: Reference/contexts/delete.md
    - reset: Reference/contexts/reset.md
    - use: Reference/contexts/use.md
    - environments:
      - clear: Reference/contexts/environments/clear.md
      - get: Reference/contexts/environments/get.md
      - use: Reference/contexts/environments/use.md
    - broker:
      - disable: Reference/contexts/broker/disable.md
      - enable: Reference/contexts/broker/enable.md
      - set: Reference/contexts/broker/set.md
      - toggle: Reference/contexts/broker/toggle.md
  - deployments:
    - get: Reference/deployments/get.md
    - list: Reference/deployments/list.md
    - logs: Reference/deployments/logs.md
    - metrics: Reference/deployments/metrics.md
    - start: Reference/deployments/start.md
    - stop: Reference/deployments/stop.md
  - environments:
    - get: Reference/environments/get.md
    - list: Reference/environments/list.md
    - use: Reference/environments/use.md
    - sync: Reference/environments/sync.md
  - local:
    - applications:
      - convert: Reference/local/applications/convert.md
      - create: Reference/local/applications/create.md
      - list: Reference/local/applications/list.md
      - variables:
        - create: Reference/local/applications/variables/create.md
        - delete: Reference/local/applications/variables/delete.md
        - edit: Reference/local/applications/variables/edit.md
        - export: Reference/local/applications/variables/export.md
        - import: Reference/local/applications/variables/import.md
        - list: Reference/local/applications/variables/list.md
    - ide: Reference/local/ide.md
    - init: Reference/local/init.md
    - pipeline:
      - deployments:
        - create: Reference/local/pipeline/deployments/create.md
        - delete: Reference/local/pipeline/deployments/delete.md
        - edit: Reference/local/pipeline/deployments/edit.md
        - get: Reference/local/pipeline/deployments/get.md
        - list: Reference/local/pipeline/deployments/list.md
      - down: Reference/local/pipeline/down.md
      - sync: Reference/local/pipeline/sync.md
      - up: Reference/local/pipeline/up.md
      - update: Reference/local/pipeline/update.md
      - view: Reference/local/pipeline/view.md
  - organisations:
    - get: Reference/organisations/get.md
  - projects:
    - patch: Reference/projects/patch.md
    - get: Reference/projects/get.md
    - list: Reference/projects/list.md
  - status: Reference/status.md
  - topics:
    - get: Reference/topics/get.md
    - list: Reference/topics/list.md
  - update: Reference/update.md
  - users:
    - audit: Reference/users/audit.md
    - permissions:
      - copy: Reference/users/permissions/copy.md
      - delete: Reference/users/permissions/delete.md
      - edit: Reference/users/permissions/edit.md
      - get: Reference/users/permissions/get.md
      - list: Reference/users/permissions/list.md
      - set: Reference/users/permissions/set.md
    - tokens:
      - create: Reference/users/tokens/create.md
      - edit: Reference/users/tokens/edit.md
      - list: Reference/users/tokens/list.md
      - revoke: Reference/users/tokens/revoke.md
    - current: Reference/users/current.md
    - list: Reference/users/list.md
  - use: Reference/use.md
...
