site_name: Quix Docs
site_description: Quix CLI Documentation
docs_dir: docs/
repo_name: quixio/quix-cli
repo_url: https://github.com/quixio/quix-cli
edit_uri: tree/main/docs
exclude_docs: '*.gen.md'
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: light blue
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.path
  - navigation.indexes
  - content.tabs.link
markdown_extensions:
- attr_list
- md_in_html
- admonition
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
- pymdownx.details: 
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
plugins:
- include-markdown
nav:
- 'Overview': 'overview.md'
- 'Quickstart': 'cli-quickstart.md'
- 'Local Development': 'cli-local-debug.md'
- 'Local Secrets': 'cli-local-secrets.md'
- 'Commands Summary': 'cli-commands-summary.md'
- 'How-To guides':
  - 'Using the CLI with GitHub Actions': 'How-To/cli-github-actions.md'
- Yaml Reference:
  - 'Pipeline YAML (quix.yaml)': 'yaml-reference/pipeline-descriptor.md'
  - 'Application YAML (app.yaml)': 'yaml-reference/app-descriptor.md'
- CLI Reference:
  - Cloud Commands:
    - CLI Reference/cloud/index.md
    - cloud apps:
      - CLI Reference/cloud/apps/index.md
      - cloud apps get: CLI Reference/cloud/apps/get.md
      - cloud apps list: CLI Reference/cloud/apps/list.md
      - cloud apps library:
        - CLI Reference/cloud/apps/library/index.md
        - cloud apps library list: CLI Reference/cloud/apps/library/list.md
    - cloud deployments:
      - CLI Reference/cloud/deployments/index.md
      - cloud deployments get: CLI Reference/cloud/deployments/get.md
      - cloud deployments list: CLI Reference/cloud/deployments/list.md
      - cloud deployments logs: CLI Reference/cloud/deployments/logs.md
      - cloud deployments metrics: CLI Reference/cloud/deployments/metrics.md
      - cloud deployments start: CLI Reference/cloud/deployments/start.md
      - cloud deployments stop: CLI Reference/cloud/deployments/stop.md
    - cloud environments:
      - CLI Reference/cloud/environments/index.md
      - cloud environments get: CLI Reference/cloud/environments/get.md
      - cloud environments list: CLI Reference/cloud/environments/list.md
      - cloud environments use: CLI Reference/cloud/environments/use.md
      - cloud environments sync: CLI Reference/cloud/environments/sync.md
      - cloud environments tokens:
        - CLI Reference/cloud/environments/tokens/index.md
        - cloud environments tokens get: CLI Reference/cloud/environments/tokens/get.md
        - cloud environments tokens rotate: CLI Reference/cloud/environments/tokens/rotate.md
    - cloud organisations:
      - CLI Reference/cloud/organisations/index.md
      - cloud organisations get: CLI Reference/cloud/organisations/get.md
    - cloud projects:
      - CLI Reference/cloud/projects/index.md
      - cloud projects patch: CLI Reference/cloud/projects/patch.md
      - cloud projects get: CLI Reference/cloud/projects/get.md
      - cloud projects list: CLI Reference/cloud/projects/list.md
    - cloud topics:
      - CLI Reference/cloud/topics/index.md
      - cloud topics get: CLI Reference/cloud/topics/get.md
      - cloud topics list: CLI Reference/cloud/topics/list.md
    - cloud users:
      - CLI Reference/cloud/users/index.md
      - cloud users audit: CLI Reference/cloud/users/audit.md
      - cloud users permissions:
        - CLI Reference/cloud/users/permissions/index.md
        - cloud users permissions copy: CLI Reference/cloud/users/permissions/copy.md
        - cloud users permissions delete: CLI Reference/cloud/users/permissions/delete.md
        - cloud users permissions edit: CLI Reference/cloud/users/permissions/edit.md
        - cloud users permissions get: CLI Reference/cloud/users/permissions/get.md
        - cloud users permissions list: CLI Reference/cloud/users/permissions/list.md
        - cloud users permissions set: CLI Reference/cloud/users/permissions/set.md
      - cloud users tokens:
        - CLI Reference/cloud/users/tokens/index.md
        - cloud users tokens create: CLI Reference/cloud/users/tokens/create.md
        - cloud users tokens edit: CLI Reference/cloud/users/tokens/edit.md
        - cloud users tokens list: CLI Reference/cloud/users/tokens/list.md
        - cloud users tokens revoke: CLI Reference/cloud/users/tokens/revoke.md
      - cloud users current: CLI Reference/cloud/users/current.md
      - cloud users list: CLI Reference/cloud/users/list.md
  - Local Commands:
    - apps:
      - CLI Reference/apps/index.md
      - apps library: CLI Reference/apps/library.md
      - apps update: CLI Reference/apps/update.md
      - apps convert: CLI Reference/apps/convert.md
      - apps create: CLI Reference/apps/create.md
      - apps delete: CLI Reference/apps/delete.md
      - apps edit: CLI Reference/apps/edit.md
      - apps list: CLI Reference/apps/list.md
      - apps variables:
        - CLI Reference/apps/variables/index.md
        - apps variables create: CLI Reference/apps/variables/create.md
        - apps variables delete: CLI Reference/apps/variables/delete.md
        - apps variables edit: CLI Reference/apps/variables/edit.md
        - apps variables export: CLI Reference/apps/variables/export.md
        - apps variables import: CLI Reference/apps/variables/import.md
        - apps variables list: CLI Reference/apps/variables/list.md
    - broker:
      - CLI Reference/broker/index.md
      - broker down: CLI Reference/broker/down.md
      - broker up: CLI Reference/broker/up.md
      - broker topics:
        - CLI Reference/broker/topics/index.md
        - broker topics list: CLI Reference/broker/topics/list.md
        - broker topics read: CLI Reference/broker/topics/read.md
        - broker topics update: CLI Reference/broker/topics/update.md
        - broker topics write: CLI Reference/broker/topics/write.md
    - init: CLI Reference/init.md
    - pipeline:
      - CLI Reference/pipeline/index.md
      - pipeline deployments:
        - CLI Reference/pipeline/deployments/index.md
        - pipeline deployments create: CLI Reference/pipeline/deployments/create.md
        - pipeline deployments delete: CLI Reference/pipeline/deployments/delete.md
        - pipeline deployments edit: CLI Reference/pipeline/deployments/edit.md
        - pipeline deployments get: CLI Reference/pipeline/deployments/get.md
        - pipeline deployments list: CLI Reference/pipeline/deployments/list.md
      - pipeline down: CLI Reference/pipeline/down.md
      - pipeline logs: CLI Reference/pipeline/logs.md
      - pipeline start: CLI Reference/pipeline/start.md
      - pipeline status: CLI Reference/pipeline/status.md
      - pipeline stop: CLI Reference/pipeline/stop.md
      - pipeline sync: CLI Reference/pipeline/sync.md
      - pipeline up: CLI Reference/pipeline/up.md
      - pipeline update: CLI Reference/pipeline/update.md
      - pipeline view: CLI Reference/pipeline/view.md
      - pipeline topics:
        - CLI Reference/pipeline/topics/index.md
        - pipeline topics create: CLI Reference/pipeline/topics/create.md
        - pipeline topics delete: CLI Reference/pipeline/topics/delete.md
        - pipeline topics edit: CLI Reference/pipeline/topics/edit.md
        - pipeline topics get: CLI Reference/pipeline/topics/get.md
        - pipeline topics list: CLI Reference/pipeline/topics/list.md
    - run: CLI Reference/run.md
    - sdk:
      - CLI Reference/sdk/index.md
      - sdk broker:
        - CLI Reference/sdk/broker/index.md
        - sdk broker cloud: CLI Reference/sdk/broker/cloud.md
        - sdk broker current: CLI Reference/sdk/broker/current.md
        - sdk broker local: CLI Reference/sdk/broker/local.md
        - sdk broker pipeline: CLI Reference/sdk/broker/pipeline.md
        - sdk broker set: CLI Reference/sdk/broker/set.md
        - sdk broker update: CLI Reference/sdk/broker/update.md
  - Other Commands:
    - logout: CLI Reference/logout.md
    - login: CLI Reference/login.md
    - contexts:
      - CLI Reference/contexts/index.md
      - contexts create: CLI Reference/contexts/create.md
      - contexts current: CLI Reference/contexts/current.md
      - contexts list: CLI Reference/contexts/list.md
      - contexts delete: CLI Reference/contexts/delete.md
      - contexts reset: CLI Reference/contexts/reset.md
      - contexts use: CLI Reference/contexts/use.md
      - contexts environments:
        - CLI Reference/contexts/environments/index.md
        - contexts environments clear: CLI Reference/contexts/environments/clear.md
        - contexts environments get: CLI Reference/contexts/environments/get.md
        - contexts environments use: CLI Reference/contexts/environments/use.md
    - status: CLI Reference/status.md
    - update: CLI Reference/update.md
    - use: CLI Reference/use.md
...
