site_name: Quix Docs
site_description: Quix CLI Documentation
docs_dir: docs/
repo_name: quixio/quix-cli
repo_url: https://github.com/quixio/quix-cli
edit_uri: tree/main/docs
exclude_docs: '*.gen.md'
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: light blue
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.path
  - navigation.indexes
  - content.tabs.link
markdown_extensions:
- attr_list
- md_in_html
- admonition
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
- pymdownx.details: 
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
plugins:
- include-markdown
nav:
- 'Overview': 'overview.md'
- 'Quickstart': 'cli-quickstart.md'
- 'Tutorials':
  - 'Using the CLI with a template': 'cli-template.md'
  - 'Using the CLI with GitHub Actions': 'cli-github-actions.md'
- Reference:
  - Other Commands:
    - contexts:
      - Reference/contexts/index.md
      - contexts broker:
        - Reference/contexts/broker/index.md
        - contexts broker cloud: Reference/contexts/broker/cloud.md
        - contexts broker local: Reference/contexts/broker/local.md
        - contexts broker set: Reference/contexts/broker/set.md
      - contexts create: Reference/contexts/create.md
      - contexts current: Reference/contexts/current.md
      - contexts list: Reference/contexts/list.md
      - contexts delete: Reference/contexts/delete.md
      - contexts reset: Reference/contexts/reset.md
      - contexts use: Reference/contexts/use.md
      - contexts environments:
        - Reference/contexts/environments/index.md
        - contexts environments clear: Reference/contexts/environments/clear.md
        - contexts environments get: Reference/contexts/environments/get.md
        - contexts environments use: Reference/contexts/environments/use.md
    - status: Reference/status.md
    - use: Reference/use.md
    - login: Reference/login.md
    - update: Reference/update.md
  - Local Commands:
    - applications:
      - Reference/applications/index.md
      - applications convert: Reference/applications/convert.md
      - applications create: Reference/applications/create.md
      - applications list: Reference/applications/list.md
      - applications variables:
        - Reference/applications/variables/index.md
        - applications variables create: Reference/applications/variables/create.md
        - applications variables delete: Reference/applications/variables/delete.md
        - applications variables edit: Reference/applications/variables/edit.md
        - applications variables export: Reference/applications/variables/export.md
        - applications variables import: Reference/applications/variables/import.md
        - applications variables list: Reference/applications/variables/list.md
    - pipeline:
      - Reference/pipeline/index.md
      - pipeline broker:
        - Reference/pipeline/broker/index.md
        - pipeline broker down: Reference/pipeline/broker/down.md
        - pipeline broker up: Reference/pipeline/broker/up.md
      - pipeline deployments:
        - Reference/pipeline/deployments/index.md
        - pipeline deployments create: Reference/pipeline/deployments/create.md
        - pipeline deployments delete: Reference/pipeline/deployments/delete.md
        - pipeline deployments edit: Reference/pipeline/deployments/edit.md
        - pipeline deployments get: Reference/pipeline/deployments/get.md
        - pipeline deployments list: Reference/pipeline/deployments/list.md
      - pipeline down: Reference/pipeline/down.md
      - pipeline status: Reference/pipeline/status.md
      - pipeline sync: Reference/pipeline/sync.md
      - pipeline up: Reference/pipeline/up.md
      - pipeline update: Reference/pipeline/update.md
      - pipeline view: Reference/pipeline/view.md
    - init: Reference/init.md
    - ide: Reference/ide.md
    - sdk:
      - Reference/sdk/index.md
      - sdk broker:
        - Reference/sdk/broker/index.md
        - sdk broker cloud: Reference/sdk/broker/cloud.md
        - sdk broker local: Reference/sdk/broker/local.md
        - sdk broker update: Reference/sdk/broker/update.md
  - Cloud Commands:
    - Reference/cloud/index.md
    - cloud applications:
      - Reference/cloud/applications/index.md
      - cloud applications get: Reference/cloud/applications/get.md
      - cloud applications list: Reference/cloud/applications/list.md
      - cloud applications library:
        - Reference/cloud/applications/library/index.md
        - cloud applications library list: Reference/cloud/applications/library/list.md
    - cloud deployments:
      - Reference/cloud/deployments/index.md
      - cloud deployments get: Reference/cloud/deployments/get.md
      - cloud deployments list: Reference/cloud/deployments/list.md
      - cloud deployments logs: Reference/cloud/deployments/logs.md
      - cloud deployments metrics: Reference/cloud/deployments/metrics.md
      - cloud deployments start: Reference/cloud/deployments/start.md
      - cloud deployments stop: Reference/cloud/deployments/stop.md
    - cloud environments:
      - Reference/cloud/environments/index.md
      - cloud environments get: Reference/cloud/environments/get.md
      - cloud environments list: Reference/cloud/environments/list.md
      - cloud environments use: Reference/cloud/environments/use.md
      - cloud environments sync: Reference/cloud/environments/sync.md
    - cloud organisations:
      - Reference/cloud/organisations/index.md
      - cloud organisations get: Reference/cloud/organisations/get.md
    - cloud projects:
      - Reference/cloud/projects/index.md
      - cloud projects patch: Reference/cloud/projects/patch.md
      - cloud projects get: Reference/cloud/projects/get.md
      - cloud projects list: Reference/cloud/projects/list.md
    - cloud topics:
      - Reference/cloud/topics/index.md
      - cloud topics get: Reference/cloud/topics/get.md
      - cloud topics list: Reference/cloud/topics/list.md
    - cloud users:
      - Reference/cloud/users/index.md
      - cloud users audit: Reference/cloud/users/audit.md
      - cloud users permissions:
        - Reference/cloud/users/permissions/index.md
        - cloud users permissions copy: Reference/cloud/users/permissions/copy.md
        - cloud users permissions delete: Reference/cloud/users/permissions/delete.md
        - cloud users permissions edit: Reference/cloud/users/permissions/edit.md
        - cloud users permissions get: Reference/cloud/users/permissions/get.md
        - cloud users permissions list: Reference/cloud/users/permissions/list.md
        - cloud users permissions set: Reference/cloud/users/permissions/set.md
      - cloud users tokens:
        - Reference/cloud/users/tokens/index.md
        - cloud users tokens create: Reference/cloud/users/tokens/create.md
        - cloud users tokens edit: Reference/cloud/users/tokens/edit.md
        - cloud users tokens list: Reference/cloud/users/tokens/list.md
        - cloud users tokens revoke: Reference/cloud/users/tokens/revoke.md
      - cloud users current: Reference/cloud/users/current.md
      - cloud users list: Reference/cloud/users/list.md
...
